version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
