using System.Runtime.InteropServices;
using System.Windows.Threading;
using Forms = System.Windows.Forms;

namespace VolturaAir.Host.Tests;

public sealed partial class PointerHighlightForegroundMonitorTests
{
    [Fact]
    public void NativeHookRefreshesForForegroundEventsGeneratedByTheHostProcess()
    {
        var log = new ForegroundLog();
        var eventWindow = new Forms.NativeWindow();
        eventWindow.CreateHandle(new Forms.CreateParams { Parent = new nint(-3) });
        try
        {
            using var monitor = new PointerHighlightForegroundMonitor(log);
            Assert.True(log.Started);
            var initialRefreshes = log.Refreshes;

            // Host-owned windows must participate in foreground updates too. Raise their
            // native event without changing the user's foreground window.
            NotifyWinEvent(0x0003, eventWindow.Handle, 0, 0);
            PumpFor(350);

            Assert.True(log.Refreshes > initialRefreshes,
                "The foreground monitor ignored an event generated by its own process.");
            monitor.Dispose();
            var disposedRefreshes = log.Refreshes;
            NotifyWinEvent(0x0003, eventWindow.Handle, 0, 0);
            PumpFor(350);
            Assert.Equal(disposedRefreshes, log.Refreshes);
        }
        finally
        {
            eventWindow.DestroyHandle();
        }
    }

    [Fact]
    public void StaleNotificationEventDoesNotClearTheCurrentAdministratorWindow()
    {
        nint foreground = 2;
        var changes = new List<bool>();
        using var monitor = new PointerHighlightForegroundMonitor(
            NullAppLog.Instance,
            8192,
            () => foreground,
            window => window == 2 ? 12288u : 8192u);
        monitor.RemoteInputBlockedChanged += (_, e) => changes.Add(e.IsBlocked);

        ForegroundChanged(monitor, 2);
        PumpFor(250);
        ForegroundChanged(monitor, 1); // A queued normal-window event arrives after Alt+Tab.
        PumpFor(250);

        Assert.True(monitor.IsRemoteInputBlocked);
        Assert.Equal([true], changes);

        foreground = 1;
        ForegroundChanged(monitor, 2); // The inverse stale event must not leave input blocked.
        PumpFor(250);
        Assert.False(monitor.IsRemoteInputBlocked);

        foreground = 2;
        ForegroundChanged(monitor, 1);
        PumpFor(250);
        Assert.True(monitor.IsRemoteInputBlocked);
        Assert.Equal([true, false, true], changes);
    }

    [Fact]
    public void DismissingNotificationDoesNotStartAnotherElevationEpisode()
    {
        nint foreground = 2;
        var changes = new List<bool>();
        using var monitor = new PointerHighlightForegroundMonitor(
            NullAppLog.Instance, 8192, () => foreground,
            window => window == 2 ? 12288u : 4096u);
        monitor.RemoteInputBlockedChanged += (_, e) => changes.Add(e.IsBlocked);
        ForegroundChanged(monitor, 2);
        PumpFor(250);

        foreground = 1; // Clicking the Windows notification briefly focuses the shell.
        ForegroundChanged(monitor, 1);
        Assert.True(monitor.IsRemoteInputBlocked);
        foreground = 2;
        ForegroundChanged(monitor, 2);
        PumpFor(250);

        Assert.True(monitor.IsRemoteInputBlocked);
        Assert.Equal([true], changes);
    }

    [Fact]
    public void UnavailableForegroundIntegrityClearsTheElevationStatus()
    {
        uint? integrity = 12288;
        using var monitor = new PointerHighlightForegroundMonitor(
            NullAppLog.Instance, 8192, () => 2, _ => integrity);
        ForegroundChanged(monitor, 2);
        PumpFor(250);
        Assert.True(monitor.IsRemoteInputBlocked);

        integrity = null;
        ForegroundChanged(monitor, 2);
        PumpFor(250);

        Assert.False(monitor.IsRemoteInputBlocked);
    }

    [Fact]
    public void DisposalIgnoresLateForegroundEvents()
    {
        var reads = 0;
        using var monitor = new PointerHighlightForegroundMonitor(
            NullAppLog.Instance, 8192, () => { reads++; return 2; }, _ => 12288);
        ForegroundChanged(monitor, 2);
        monitor.Dispose();

        ForegroundChanged(monitor, 2);
        PumpFor(250);

        Assert.Equal(0, reads);
        Assert.False(monitor.IsRemoteInputBlocked);
    }

    private static void ForegroundChanged(PointerHighlightForegroundMonitor monitor, nint eventWindow) =>
        monitor.OnForegroundWindowChanged(0, 0x0003, eventWindow, 0, 0, 0, 0);

    private sealed class ForegroundLog : IAppLogWriter
    {
        public bool Started { get; private set; }
        public int Refreshes { get; private set; }

        public void Write(AppLogEntry entry)
        {
            Started |= entry.Outcome == "started";
            if (entry.Action == "foreground_input_monitor" &&
                entry.Outcome?.StartsWith("foreground_", StringComparison.Ordinal) == true)
            {
                Refreshes++;
            }
        }
    }

    [LibraryImport("user32.dll")]
    [DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
    private static partial void NotifyWinEvent(uint eventType, nint window, int objectId, int childId);

    private static void PumpFor(int milliseconds)
    {
        var frame = new DispatcherFrame();
        var timer = new DispatcherTimer(DispatcherPriority.ApplicationIdle)
        {
            Interval = TimeSpan.FromMilliseconds(milliseconds)
        };
        timer.Tick += (_, _) => frame.Continue = false;
        timer.Start();
        try
        {
            Dispatcher.PushFrame(frame);
        }
        finally
        {
            timer.Stop();
        }
    }
}
