using System.Diagnostics;
using System.Security;
using Microsoft.Win32;

namespace VolturaAir.Host;

public static class AppTextDestinationDraftSettings
{
    private static string SettingsKeyPath => HostSettingsRegistry.SettingsKeyPath;
    private const string AutomaticallyRemoveDraftFilesValueName = "AutomaticallyRemoveTextDestinationDraftFiles";

    public static bool AutomaticallyRemoveDraftFiles()
    {
        using var key = Registry.CurrentUser.OpenSubKey(SettingsKeyPath, writable: false);
        return key?.GetValue(AutomaticallyRemoveDraftFilesValueName) is not int value || value != 0;
    }

    public static void SetAutomaticallyRemoveDraftFiles(bool automaticallyRemoveDraftFiles)
    {
        using var key = Registry.CurrentUser.OpenSubKey(SettingsKeyPath, writable: true) ?? Registry.CurrentUser.CreateSubKey(SettingsKeyPath, writable: true);
        key.SetValue(AutomaticallyRemoveDraftFilesValueName, automaticallyRemoveDraftFiles ? 1 : 0, RegistryValueKind.DWord);
    }
}

internal sealed record TextDestinationDraft(string Path, DateTime DeleteAfterLocal, bool AutomaticallyRemove);

internal static class TextDestinationDraftStore
{
    private static readonly TimeSpan CleanupAge = TimeSpan.FromDays(1);
    private static readonly HashSet<string> DraftExtensions = new(StringComparer.OrdinalIgnoreCase) { ".docx", ".txt", ".xlsx" };

    public static TextDestinationDraft CreateDraft(string extension)
    {
        var directory = GetDirectory();
        Directory.CreateDirectory(directory);
        return new(
            Path.Combine(directory, $"Untitled-{Guid.NewGuid():N}{extension}"),
            DateTime.Now + CleanupAge,
            AppTextDestinationDraftSettings.AutomaticallyRemoveDraftFiles());
    }

    public static IAsyncDisposable CreateCleanupService(IAppLog appLog) => new TextDestinationDraftCleanup(appLog);

    public static bool TryOpenFolder()
    {
        try
        {
            var directory = GetDirectory();
            Directory.CreateDirectory(directory);
            Process.Start(new ProcessStartInfo(directory) { UseShellExecute = true });
            return true;
        }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or InvalidOperationException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    public static IReadOnlyList<string> GetNoticeLines(TextDestinationDraft draft) => draft.AutomaticallyRemove
        ?
        [
            $"File: {draft.Path}",
            "Auto-generated by Voltura Air.",
            $"Scheduled for removal on {draft.DeleteAfterLocal:yyyy-MM-dd}.",
            "To keep this file, use Save As with a different filename.",
            "Control automatic removal in Preferences > Text destination > Keep generated draft files."
        ]
        :
        [
            $"File: {draft.Path}",
            "Auto-generated by Voltura Air.",
            "This generated draft is being kept until you remove it.",
            "Control this in Preferences > Text destination > Keep generated draft files."
        ];

    internal static void DeleteExpiredIfEnabled()
    {
        if (!AppTextDestinationDraftSettings.AutomaticallyRemoveDraftFiles()) return;
        DeleteExpired(GetDirectory(), DateTime.UtcNow - CleanupAge);
    }

    internal static void DeleteExpired(string directory, DateTime cutoffUtc)
    {
        if (!Directory.Exists(directory)) return;
        foreach (var path in Directory.EnumerateFiles(directory, "Untitled-*.*", SearchOption.TopDirectoryOnly))
        {
            try
            {
                var draft = new FileInfo(path);
                if (!DraftExtensions.Contains(draft.Extension) || draft.CreationTimeUtc > cutoffUtc) continue;
                using (File.Open(path, FileMode.Open, FileAccess.Read, FileShare.None)) { }
                File.Delete(path);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                // A target application can still own the file. Preserve it and
                // reconsider it during the next cleanup interval.
            }
        }
    }

    private static string GetDirectory() => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Voltura Air", "Text destination drafts");
}

internal sealed class TextDestinationDraftCleanup : IAsyncDisposable
{
    private readonly IAppLog _appLog;
    private readonly Action _cleanup;
    private readonly System.Threading.Timer _timer;
    private int _cleanupRunning;

    public TextDestinationDraftCleanup(IAppLog appLog)
        : this(appLog, TextDestinationDraftStore.DeleteExpiredIfEnabled, TimeSpan.Zero, TimeSpan.FromHours(1))
    {
    }

    internal TextDestinationDraftCleanup(IAppLog appLog, Action cleanup, TimeSpan dueTime, TimeSpan period)
    {
        _appLog = appLog;
        _cleanup = cleanup;
        _timer = new System.Threading.Timer(RunCleanup, null, dueTime, period);
    }

    public ValueTask DisposeAsync() => _timer.DisposeAsync();

    private void RunCleanup(object? state)
    {
        if (Interlocked.Exchange(ref _cleanupRunning, 1) != 0)
        {
            return;
        }

        try
        {
            _cleanup();
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or SecurityException)
        {
            try
            {
                _appLog.Write(new AppLogEntry(
                    Event: "host_maintenance",
                    Source: "windows_host",
                    Action: "text_destination_draft_cleanup",
                    Outcome: "failed",
                    Detail: ex.Message));
            }
            catch (Exception logException) when (logException is not OutOfMemoryException)
            {
                // A maintenance timer must not terminate the host because an injected logger failed.
            }
        }
        finally
        {
            Volatile.Write(ref _cleanupRunning, 0);
        }
    }
}
