using System.Diagnostics;
using Microsoft.Win32;

namespace VolturaAir.Host;

public static class AppTextDestinationDraftSettings
{
    private const string SettingsKeyPath = @"Software\VolturaAir";
    private const string AutomaticallyRemoveDraftFilesValueName = "AutomaticallyRemoveTextDestinationDraftFiles";

    public static bool AutomaticallyRemoveDraftFiles()
    {
        using var key = Registry.CurrentUser.OpenSubKey(SettingsKeyPath, writable: false);
        return key?.GetValue(AutomaticallyRemoveDraftFilesValueName) is int value ? value != 0 : true;
    }

    public static void SetAutomaticallyRemoveDraftFiles(bool automaticallyRemoveDraftFiles)
    {
        using var key = Registry.CurrentUser.OpenSubKey(SettingsKeyPath, writable: true) ?? Registry.CurrentUser.CreateSubKey(SettingsKeyPath, writable: true);
        key.SetValue(AutomaticallyRemoveDraftFilesValueName, automaticallyRemoveDraftFiles ? 1 : 0, RegistryValueKind.DWord);
    }
}

internal sealed record TextDestinationDraft(string Path, DateTime DeleteAfterLocal, bool AutomaticallyRemove);

internal static class TextDestinationDraftStore
{
    private static readonly TimeSpan CleanupAge = TimeSpan.FromDays(1);
    private static readonly HashSet<string> DraftExtensions = new(StringComparer.OrdinalIgnoreCase) { ".docx", ".txt", ".xlsx" };

    public static TextDestinationDraft CreateDraft(string extension)
    {
        var directory = GetDirectory();
        Directory.CreateDirectory(directory);
        return new(
            Path.Combine(directory, $"Untitled-{Guid.NewGuid():N}{extension}"),
            DateTime.Now + CleanupAge,
            AppTextDestinationDraftSettings.AutomaticallyRemoveDraftFiles());
    }

    public static IDisposable CreateCleanupService() => new TextDestinationDraftCleanup();

    public static bool TryOpenFolder()
    {
        try
        {
            var directory = GetDirectory();
            Directory.CreateDirectory(directory);
            Process.Start(new ProcessStartInfo(directory) { UseShellExecute = true });
            return true;
        }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or InvalidOperationException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    public static IReadOnlyList<string> GetNoticeLines(TextDestinationDraft draft) => draft.AutomaticallyRemove
        ?
        [
            $"File: {draft.Path}",
            "Auto-generated by Voltura Air.",
            $"Scheduled for removal on {draft.DeleteAfterLocal:yyyy-MM-dd}.",
            "To keep this file, use Save As with a different filename.",
            "Control automatic removal in Preferences > Text destination > Keep generated draft files."
        ]
        :
        [
            $"File: {draft.Path}",
            "Auto-generated by Voltura Air.",
            "This generated draft is being kept until you remove it.",
            "Control this in Preferences > Text destination > Keep generated draft files."
        ];

    internal static void DeleteExpiredIfEnabled()
    {
        if (!AppTextDestinationDraftSettings.AutomaticallyRemoveDraftFiles()) return;
        DeleteExpired(GetDirectory(), DateTime.UtcNow - CleanupAge);
    }

    internal static void DeleteExpired(string directory, DateTime cutoffUtc)
    {
        if (!Directory.Exists(directory)) return;
        foreach (var path in Directory.EnumerateFiles(directory, "Untitled-*.*", SearchOption.TopDirectoryOnly))
        {
            try
            {
                var draft = new FileInfo(path);
                if (!DraftExtensions.Contains(draft.Extension) || draft.CreationTimeUtc > cutoffUtc) continue;
                using (File.Open(path, FileMode.Open, FileAccess.Read, FileShare.None)) { }
                File.Delete(path);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                // A target application can still own the file. Preserve it and
                // reconsider it during the next cleanup interval.
            }
        }
    }

    private static string GetDirectory() => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Voltura Air", "Text destination drafts");
}

internal sealed class TextDestinationDraftCleanup : IDisposable
{
    private readonly System.Threading.Timer _timer = new(_ => _ = Task.Run(TextDestinationDraftStore.DeleteExpiredIfEnabled), null, TimeSpan.Zero, TimeSpan.FromHours(1));

    public void Dispose() => _timer.Dispose();
}
