// <auto-generated />
// Generated from assets/ui-tokens.json. Do not edit directly.
namespace VolturaAir.Host;

internal static class UiTokens
{
    public const double SpaceNone = 0d;
    public const double Space2xs = 2d;
    public const double SpaceXs = 4d;
    public const double SpaceSm = 8d;
    public const double SpaceMd = 12d;
    public const double SpaceLg = 16d;
    public const double SpaceXl = 24d;
    public const double Space2xl = 32d;
    public const double Space3xl = 40d;

    public static ThemePalette DarkPalette { get; } = new(
        true,
        System.Drawing.Color.FromArgb(16, 20, 24),
        System.Drawing.Color.FromArgb(23, 29, 33),
        System.Drawing.Color.FromArgb(32, 40, 46),
        System.Drawing.Color.FromArgb(247, 242, 233),
        System.Drawing.Color.FromArgb(185, 194, 199),
        System.Drawing.Color.FromArgb(62, 74, 82),
        System.Drawing.Color.FromArgb(18, 168, 148),
        System.Drawing.Color.FromArgb(15, 123, 108),
        System.Drawing.Color.FromArgb(255, 255, 255),
        System.Drawing.Color.FromArgb(247, 242, 233),
        System.Drawing.Color.FromArgb(8, 122, 96),
        System.Drawing.Color.FromArgb(255, 116, 95),
        System.Drawing.Color.FromArgb(192, 83, 58),
        System.Drawing.Color.FromArgb(255, 255, 255));

    public static ThemePalette LightPalette { get; } = new(
        false,
        System.Drawing.Color.FromArgb(246, 248, 250),
        System.Drawing.Color.FromArgb(255, 255, 255),
        System.Drawing.Color.FromArgb(237, 242, 245),
        System.Drawing.Color.FromArgb(28, 34, 39),
        System.Drawing.Color.FromArgb(93, 104, 112),
        System.Drawing.Color.FromArgb(211, 220, 226),
        System.Drawing.Color.FromArgb(15, 143, 128),
        System.Drawing.Color.FromArgb(15, 123, 108),
        System.Drawing.Color.FromArgb(255, 255, 255),
        System.Drawing.Color.FromArgb(28, 34, 39),
        System.Drawing.Color.FromArgb(8, 122, 96),
        System.Drawing.Color.FromArgb(192, 83, 58),
        System.Drawing.Color.FromArgb(192, 83, 58),
        System.Drawing.Color.FromArgb(255, 255, 255));
}
